apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crunchy-postgres
  template:
    metadata:
      labels:
        app: crunchy-postgres
    spec:
      containers:
        - resources: {}
          name: postgres
          image: postgres
          envFrom:
          - secretRef:
              name: postgres-secret
          ports:
          - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-pvc