apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: postgres
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: postgres

resources:
  - deployment.yaml
  - pvc.yaml
  - routes.yaml
  - secret.yaml
  - service.yaml

commonAnnotations:
    argocd.argoproj.io/sync-wave: "1"