apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhbk.yaml
  - 3scale
  - 3scale-apicast
  #- object-datastore.yaml

commonAnnotations:
    argocd.argoproj.io/sync-wave: "0"