kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager-noprod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  wildcardDomain: apps.cluster-f78kj.dynamic.redhatworkshops.io
  system:
    fileStorage:
      persistent: false
      s3:
        bucket: system-storage
        region: us-east-1
        accessKeyId: minio
        secretAccessKey: minio123
        endpoint: http://minio.minio.svc:9000  # Cambia según el nombre del service y namespace
        protocol: http
        configuration:
          s3ForcePathStyle: 'true'