kind: APIManager
apiVersion: apps.3scale.net/v1alpha1
metadata:
  name: apimanager-noprod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  wildcardDomain: apps.cluster-f78kj.dynamic.redhatworkshops.io
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: ocs-external-storagecluster-cephfs