apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale

resources:
  - ../../base
  - 3scale-instance.yaml
  - 3s-auth.yaml
  #- tenants_post-hook.yaml

commonAnnotations:
    argocd.argoproj.io/sync-wave: "4"