apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

resources:
  - ../../base
  - ../../../../../components/apps/minio-bucket/overlays/default
patchesStrategicMerge:
  - patch-create-bucket-job.yaml