apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-check-operator
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: hook-sa
      containers:
        - name: check-operator
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Esperando que el operador Red Hat Integration - 3scale esté instalado..."
              STARTINGCSV=$(oc get subscriptions.operators.coreos.com 3scale-operator -o jsonpath='{.spec.startingCSV}')
              for i in {1..30}; do
                STATUS=$(oc get csv "${STARTINGCSV}" -o jsonpath='{.status.phase}')

                if [[ "$STATUS" != "Succeeded" ]]; then
                  echo "[Intento $i] El operador Red Hat Integration - 3scale aún no está instalado. Esperando 30s..."
                  sleep 30
                  continue
                fi
                
                echo "El operador Red Hat Integration - 3scale está instalado correctamente"
                exit 0
              done

              echo "Timeout esperando que el operador esté instalado"
              exit 1
      restartPolicy: Never
