apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hook-role
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions"]
    verbs: ["get", "list"]
  - apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions"]
    verbs: ["get", "list"]
