apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hook-binding
subjects:
  - kind: ServiceAccount
    name: hook-sa
    namespace: ""
roleRef:
  kind: Role
  name: hook-role
  apiGroup: rbac.authorization.k8s.io
