apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/mcaballol/platforms-gitops.git'  # Update me on fork
              revision: main
              directories:
              - path: tenants/*/*/overlays/patch-me-see-overlay
              - path: tenants/*/*/overlays/common
          - list:
              elements:
                - name: cluster-a
                  server: https://kubernetes.default.svc


  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}'
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        tenant: '{{path[1]}}'
    spec:
      project: tenants
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 20m
      source:
        repoURL: 'https://github.com/mcaballol/platforms-gitops.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'