apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  logLevel: info
  pathRoutingEnabled: false
  responseCodesIncluded: true
  openSSLPeerVerificationEnabled: false
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    #limits:
    #  cpu: '1'
    #  memory: 128Mi
    #requests:
    #  cpu: 500m
    #  memory: 64Mi
  # exposedHost:
  #   host: bs-hello-java-openid-dev.apps.cluster-bcrk5.dynamic.redhatworkshops.io
  #   tls:
  #     - {}
  extendedMetrics: true
  deploymentEnvironment: staging
  adminPortalCredentialsRef:
    name: apicast-staging
  oidcLogLevel: info
  timezone: America/Lima
  replicas: 1
  managementAPIScope: status
  configurationLoadMode: lazy #boot
  cacheConfigurationSeconds: 0
