apiVersion: v1
kind: Secret
metadata:
  name: dev-admin-secret
  namespace: 3scale-tenant-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreSync
type: Opaque
stringData:
  admin_password: "devtenantpass"