apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale-tenant-dev

resources:
  - ../../base
  - dev-tenant.yaml
  - dev-admin-secret.yaml
  - apicast-production.yaml
  - apicast-staging.yaml
# commonAnnotations:
#     argocd.argoproj.io/sync-wave: "5"