apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: preset-sa-binding
subjects:
  - kind: ServiceAccount
    name: preset-sa
    namespace: ""
roleRef:
  kind: Role
  name: preset-role
  apiGroup: rbac.authorization.k8s.io
