kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
stringData:
  username: "postgres"
  password: "mysecretpassword"
type: Opaque
