apiVersion: v1
kind: Secret
metadata:
  name: qa-admin-secret
  namespace: 3scale-tenant-qa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  admin_password: "qatenantpass"