apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: qa-tenant
  namespace: 3scale-tenant-qa
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: admin
  #systemMasterUrl: https://master.apps.cluster-t2xqd.t2xqd.sandbox2018.opentlc.com
  systemMasterUrl: https://master.apps.cluster-x8cq8.dynamic.redhatworkshops.io
  email: admin@ecorp.com
  organizationName: qa
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  passwordCredentialsRef:
    name: qa-admin-secret
  tenantSecretRef:
    name: qa-tenant-secret
    